# Generated by Django 4.2 on 2023-04-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='abi',
            field=models.JSONField(default=None, null=True),
        ),
    ]
