# Generated by Django 4.1.5 on 2023-04-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="serv_name",
            field=models.CharField(default="Not Available", max_length=230),
            preserve_default=False,
        ),
    ]
