# Generated by Django 4.2 on 2023-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_group_abi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ren',
            field=models.DateTimeField(),
        ),
    ]
