# Generated by Django 4.1.5 on 2023-04-09 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0003_group_serv_acc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="ren",
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
